import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import TopNavbar from "@/components/shared/TopNavbar";
import Navbar from "@/components/shared/MiddleNavbar";
import BottomNavbar from "@/components/shared/BottomNavbar";
import Footer from "@/components/shared/Footer";

const inter = Inter({
  subsets: ["latin"],
  weight: ["400", "500", "600", "700"],
  variable: "--font-inter",
});

export const metadata: Metadata = {
  title: "Near Books",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.5.0/css/all.min.css"></link>
      <body className={`${inter.className} antialiased `}>
        <div className="hidden lg:block">
            <TopNavbar></TopNavbar>
        </div>
        
        <Navbar/>
        <BottomNavbar/>
        {children}
        <Footer/>
      </body>
    </html>
  );
}
